Controllers/ClientController.cs
using Fiap.Web.AspNet3.Data;
using Fiap.Web.AspNet3.Models;
using Fiap.Web.AspNet3.Repository;
using Fiap.Web.AspNet3.Repository.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Fiap.Web.AspNet3.Controllers
{
    public class ClientController : Controller
    {

        private readonly IClienteRepository clienteRepository;
        private readonly IRepresentanteRepository representanteRepository;

        public ClientController(IClienteRepository cliente,IRepresentanteRepository representante)
        {
            clienteRepository = cliente;
            representanteRepository = representante;
        }

        [HttpGet]
        public IActionResult Index()
        {
            //var listaClientes = clienteRepository.FindAllOrderByNomeAsc();
            //var listaClientes = clienteRepository.FindAllOrderByNomeDesc();
            // var listaClientes = clienteRepository.FindAllOrderByNome("Luan");
            ViewBag.representantes = ComboRepresentantes();

            return View();
        }


        [HttpPost]
        public IActionResult Pesquisar(ClientModel clientModel)
        {

            if (clientModel.Name == null && clientModel.Email == null && clientModel.RepresentanteId == 0)
            {
                TempData["mensagem"] = "Não foi encontrado nenhum resultado para essa pesquisa, mas veja abaixo os clientes cadastrados";
                ViewBag.clientes = ListarTodosClientes();
                ViewBag.representantes = ComboRepresentantes();
            }
            else
            {
                if(clientModel.Name == null)
                {
                    clientModel.Name = "";
                }

                if(clientModel.Email == null)
                {
                    clientModel.Email = "";
                }

                var clientes = clienteRepository.FindByNameAndEmailAndRepresentante
                    (clientModel.Name, clientModel.Email, clientModel.RepresentanteId);
                ViewBag.clientes = clientes;
                ViewBag.representantes = ComboRepresentantes();
            }

            return View("Index");
        }


        public IActionResult NewClient()
        {
            ViewBag.representantes = ComboRepresentantes();

            return View(new ClientModel());
        }

        private SelectList ComboRepresentantes()
        {
            var listaRepresentantes = representanteRepository.FindAll();
            var selectListRepresentantes = new SelectList(listaRepresentantes, "RepresentanteId", "NomeRepresentante");
            return selectListRepresentantes;
        }

        private IList<ClientModel> ListarTodosClientes()
        {
            return clienteRepository.FindAll();
        }

        [HttpPost]
        public IActionResult NewClient(ClientModel clientModel)
        {
            if (ModelState.IsValid)
            {
                clienteRepository.Insert(clientModel);
                TempData["mensagem"] = "Cliente cadastrado com sucesso";/*Retorna Mensagem de Sucesso na View*/

                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.representantes = ComboRepresentantes();

                return View(clientModel);
            }
        }


        [HttpGet]
        public IActionResult Edit(int id)
        {
            var cliente = clienteRepository.FindById(id);

            ViewBag.representantes = ComboRepresentantes();


            return View(cliente);
        }

        [HttpPost]
        public IActionResult Edit(ClientModel clientModel)/*Passar por parametro a classe e um objeto para carregar*/
        {

            if (ModelState.IsValid)
            {
                clienteRepository.Update(clientModel);
                TempData["mensagem"] = "Cliente Alterado com Sucesso"; /*Exibe Mensagem de Sucesso na View*/

                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.representantes = ComboRepresentantes();
                return View(clientModel);
            }

        }


        public IActionResult Detales(int id)
        {
            var cliente = clienteRepository.FindById(id);

            return View(cliente);
        }




    }
}

Controllers/FornecedorController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Fiap.Web.AspNet3.Data;
using Fiap.Web.AspNet3.Models;
using Fiap.Web.AspNet3.Repository;
using Fiap.Web.AspNet3.Repository.Interface;

namespace Fiap.Web.AspNet3.Controllers
{
    public class FornecedorController : Controller
    {
        private readonly IFornecedorRepository fornecedoresRepository;

        public FornecedorController(IFornecedorRepository fornecedor)
        {
            this.fornecedoresRepository = fornecedor;
        }


        public IActionResult Index()
        {
            var forn = fornecedoresRepository.FindAll();

            return View(forn);
        }


        public IActionResult Details(int id)
        {

            var fornecedorModel = fornecedoresRepository.FindById(id);
            if (fornecedorModel == null)
            {
                return NotFound();
            }

            return View(fornecedorModel);
        }

        // GET: Fornecedor/Create
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("FornecedorId,FornecedorNome,Cnpj,Telefone,Email")] FornecedorModel fornecedorModel)
        {
            if (ModelState.IsValid)
            {
                fornecedoresRepository.Insert(fornecedorModel);
                return RedirectToAction(nameof(Index));
            }
            return View(fornecedorModel);
        }

        // GET: Fornecedor/Edit/5
        public IActionResult Edit(int id)
        {
            var fornecedorModel = fornecedoresRepository.FindById(id);
            if (fornecedorModel == null)
            {
                return NotFound();
            }
            return View(fornecedorModel);
        }

        // POST: Fornecedor/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("FornecedorId,FornecedorNome,Cnpj,Telefone,Email")] FornecedorModel fornecedorModel)
        {
            if (id != fornecedorModel.FornecedorId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                fornecedoresRepository.Update(fornecedorModel);
                return RedirectToAction(nameof(Index));
            }
            return View(fornecedorModel);
        }

        // GET: Fornecedor/Delete/5
        public IActionResult Delete(int id)
        {
          

            var fornecedorModel = fornecedoresRepository.FindById(id);
            if (fornecedorModel == null)
            {
                return NotFound();
            }

            return View(fornecedorModel);
        }

        // POST: Fornecedor/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            
            var fornecedorModel = fornecedoresRepository.FindById(id);
            if (fornecedorModel != null)
            {
                fornecedoresRepository.Delete(fornecedorModel);
            }

            return RedirectToAction(nameof(Index));
        }

        
    }
}

Controllers/GerenteController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Fiap.Web.AspNet3.Data;
using Fiap.Web.AspNet3.Models;
using Fiap.Web.AspNet3.Repository;
using Fiap.Web.AspNet3.Repository.Interface;

namespace Fiap.Web.AspNet3.Controllers
{
    public class GerenteController : Controller
    {
        private readonly IGerenteRepository gerenteRepository;

        public GerenteController(IGerenteRepository gerente)
        {
            this.gerenteRepository = gerente;
        }


        /*Chamada*/
        public IActionResult Create()
        {
            return View();
        }

        /*Consulta*/

        [HttpGet]
        public IActionResult Index()
        {
            var listaGerentes = gerenteRepository.FindAll();

            return View(listaGerentes);
        }



        [HttpGet]
        public IActionResult Details(int id)
        {

            var gerenteModel = gerenteRepository.FindById(id);

            if (gerenteModel == null)
            {
                return NotFound();
            }

            return View(gerenteModel);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {

            var gerenteModel = gerenteRepository.FindById(id);
            gerenteRepository.Update(gerenteModel);


            if (gerenteModel == null)
            {
                return NotFound();
            }
            return View(gerenteModel);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var gerenteModel = gerenteRepository.FindById(id);
            gerenteRepository.Delete(gerenteModel);

            if (gerenteModel == null)
            {
                return NotFound();
            }

            return View(gerenteModel);
        }



        /*Inserir*/


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("GerenteId,Nome,Sobrenome")] GerenteModel gerenteModel)
        {
            if (ModelState.IsValid)
            {
                gerenteRepository.Insert(gerenteModel);
                return RedirectToAction(nameof(Index));
            }

            return View(gerenteModel);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("GerenteId,Nome,Sobrenome")] GerenteModel gerenteModel)
        {
            if (id != gerenteModel.GerenteId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                gerenteRepository.Update(gerenteModel);

                return RedirectToAction(nameof(Index));
            }
            return View(gerenteModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {

            var gerenteModel = gerenteRepository.FindById(id);

            if (gerenteModel != null)
            {
                gerenteRepository.Delete(gerenteModel);
            }

            return RedirectToAction(nameof(Index));
        }




    }
}

Controllers/RepresentanteController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Fiap.Web.AspNet3.Data;
using Fiap.Web.AspNet3.Models;
using Fiap.Web.AspNet3.Repository;
using Fiap.Web.AspNet3.Repository.Interface;

namespace Fiap.Web.AspNet3.Controllers
{
    public class RepresentanteController : Controller
    {


        private readonly IRepresentanteRepository representanteRepository;

        public RepresentanteController(IRepresentanteRepository repository)
        {
            representanteRepository = repository;
        }


        /*Chamada*/
        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }


        /*Consulta*/


        [HttpGet]
        public IActionResult Index()
        {
            var listaRepresentates = representanteRepository.FindAll();

            return View(listaRepresentates);
        }

        [HttpGet]
        public IActionResult Details(int id)
        {

            var representanteModel = representanteRepository.FindByIdWithClientes(id);
            if (representanteModel == null)
            {
                return NotFound();
            }

            return View(representanteModel);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {


            var representanteModel = representanteRepository.FindById(id);
            if (representanteModel == null)
            {
                return NotFound();
            }
            return View(representanteModel);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {


            var representanteModel = representanteRepository.FindById(id);
            if (representanteModel == null)
            {
                return NotFound();
            }

            return View(representanteModel);
        }
        /*Inserindo*/

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("RepresentanteId,NomeRepresentante")] RepresentanteModel representanteModel)
        {
            if (ModelState.IsValid)
            {
                representanteRepository.Insert(representanteModel);
                return RedirectToAction(nameof(Index));
            }
            return View(representanteModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("RepresentanteId,NomeRepresentante")] RepresentanteModel representanteModel)
        {
            if (id != representanteModel.RepresentanteId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

                representanteRepository.Update(representanteModel);

                return RedirectToAction(nameof(Index));
            }
            return View(representanteModel);
        }



        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
           
            var representanteModel = representanteRepository.FindById(id);
            
            if (representanteModel != null )
            {
                representanteRepository.Delete(representanteModel);
            }

            return RedirectToAction(nameof(Index));
        }

        
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Fiap.Web.AspNet3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Fiap.Web.AspNet3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">C# ASP.NET</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Client" asp-action="Index">Clientes</a>
                        </li>
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Representante" asp-action="Index">Representantes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Gerente" asp-action="Index">Gerentes</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Fornecedor" asp-action="Index">Fornecedores</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - C# MASTERING - Luan Vieira
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutDark.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Fiap.Web.AspNet3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Fiap.Web.AspNet3.styles.css" asp-append-version="true" />
</head>
<body style="background-color: darkgray">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">C# ASP.NET</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Client" asp-action="Index">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="Index">Carros</a>
                        </li>



                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            @RenderSection("Menu",required:false)

        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - C# MASTERING - <a asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>